BEGIN TRANSACTION;
CREATE TABLE df (
	"Nama Produk" TEXT, 
	"Harga Produk" BIGINT, 
	"Nama Toko" TEXT, 
	"Rating Produk" FLOAT, 
	"Paling Populer" BIGINT
);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Pendek Pria GODRIC-WHITE',259900,'MOC',5.0,0);
INSERT INTO "df" VALUES('Cotton Well Ben Short Sleeve Oxford Shirt Mint Green | Kemeja Pria Lengan Pendek Basic Polos Hijau Muda',279000,'Cotton Well',5.0,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Pendek Pria Briscoe - Olive',279900,'MOC',4.9,0);
INSERT INTO "df" VALUES('Bsc Dillion 3',559000,'Hush Puppies',4.9,1);
INSERT INTO "df" VALUES('Caspian Vertical Stripe Pattern Shirt',599000,'Obermain',4.9,1);
INSERT INTO "df" VALUES('Relaxed Fit Short Sleeve Stripes Shirt',399900,'WOOD',4.8,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Oxford Slub Regular Fit Pria Abu',399000,'Police Denim',4.9,1);
INSERT INTO "df" VALUES('Dillion 2 (Ss25)',559000,'Hush Puppies',4.8,1);
INSERT INTO "df" VALUES('Gloaming Kemeja Flanel Veterano Panjang Aquila Pria',320000,'Gloaming',4.8,1);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Oxford Slub Navy Regular Fit Pria',399000,'Police Denim',4.9,1);
INSERT INTO "df" VALUES('Dillion Ls',699000,'Hush Puppies',5.0,1);
INSERT INTO "df" VALUES('MOC Kemeja Shanghai Lengan Panjang Pria Azam - Blue',469900,'MOC',5.0,0);
INSERT INTO "df" VALUES('Bsc Dillion 3',559000,'Hush Puppies',5.0,1);
INSERT INTO "df" VALUES('MSH STRUMMER SHORT SLEEVE SHIRT WHITE',645000,'Volcom',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford Abu 1069',299000,'Platini',4.9,0);
INSERT INTO "df" VALUES('(Special Price) Platini Kemeja Polos Pria Lengan Pendek Katun Twill Hitam 73399',479000,'Platini',4.8,0);
INSERT INTO "df" VALUES('POLICE Kemeja Abstrak Printing Cotton Soft Coklat Regular Fit Pria',399000,'Police Denim',4.8,1);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Oxford Pendek Dusty Blue 1069',299000,'Platini',4.9,0);
INSERT INTO "df" VALUES('Platini Kemeja Motif Salur Pria Lengan Pendek Katun Oxford Biru Muda 73341.21',519000,'Platini',4.9,1);
INSERT INTO "df" VALUES('Regular Fit Short Sleeve Check Shirt',399900,'WOOD',4.8,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Basic Cotton Soft White Regular Fit Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Batik Pria Lengan Panjang Katun Ungu 36034',549000,'Platini',4.7,1);
INSERT INTO "df" VALUES('Bsc Dillion 3',559000,'Hush Puppies',5.0,0);
INSERT INTO "df" VALUES('Long Sleeve Micro Stripe Shirt',429900,'WOOD',5.0,1);
INSERT INTO "df" VALUES('Platini Kemeja Hawai Pria Lengan Pendek Abu 132106',479000,'Platini',4.9,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford Cream 1069',299000,'Platini',4.7,1);
INSERT INTO "df" VALUES('POLICE Kemeja Abstrak Printing Cotton Soft Putih Hijau Regular Fit Pria',399000,'Police Denim',4.8,1);
INSERT INTO "df" VALUES('Bsc Dillion 3',559000,'Hush Puppies',4.8,1);
INSERT INTO "df" VALUES('Short Sleeve Checks Shirt with Pocket',399900,'WOOD',4.9,1);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Basic Cotton Soft Regular Fit Lengan Pendek Pria',399000,'Police Denim',4.8,1);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Tencel Regular Fit Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHP Keenan S/S Blue',449000,'AMK',4.8,0);
INSERT INTO "df" VALUES('Kemeja Tangan Pendek',519000,'Andrew Smith',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford Coklat Tua 1069',299000,'Platini',4.9,1);
INSERT INTO "df" VALUES('Eaden Stand Collar Shirt',699000,'Obermain',4.4,1);
INSERT INTO "df" VALUES('Dillion 2 (Ss25)',559000,'Hush Puppies',4.9,1);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Basic Cotton Soft Grey Regular Fit Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('MOC - Kemeja Batik Pria Lengan Pendek Surasena - White Warna White',329900,'MOC',5.0,0);
INSERT INTO "df" VALUES('Dwan Casual Shirt Kemeja Polos Pria Lengan Pendek Kasual Formal Material Cotton ORIGINAL - Cream',832500,'Hamlin',4.6,0);
INSERT INTO "df" VALUES('Cotton Well Morocco Shirt Burgundy | Kemeja Koko Pria Kerah V Neck Maroon',279000,'Cotton Well',4.8,0);
INSERT INTO "df" VALUES('OXCON Utility Double Pocket Authentic Kemeja Flannel Shirt Monotone Black',390000,'Oxcon',4.7,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Regular Fit Pria',399000,'Police Denim',4.7,0);
INSERT INTO "df" VALUES('Platini Kemeja Shanghai Motif Kotak Lengan Panjang Katun 961023',519000,'Platini',4.8,1);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Pendek Katun Oxford Hitam Pekat 1069',299000,'Platini',4.9,1);
INSERT INTO "df" VALUES('Regular Fit Short Sleeve Oxford Shirt',399900,'WOOD',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Twill Regular Fit Hijau Tua Pria',399000,'Police Denim',4.9,1);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Regular Fit Pria',399000,'Police Denim',4.7,1);
INSERT INTO "df" VALUES('OXCON Kemeja collarless kerah koko Suede Kasual Pria Lengan Pendek White',235000,'Oxcon',4.7,0);
INSERT INTO "df" VALUES('Kemeja Tangan Pendek',619000,'Andrew Smith',NULL,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Stripe Cotton Soft Dark Grey Regular Fit Pria',399000,'Police Denim',4.5,0);
INSERT INTO "df" VALUES('MOC Kemeja Batik Shanghai Lengan Pendek Pria SAFIDY-KHAKI',459900,'MOC',5.0,0);
INSERT INTO "df" VALUES('Kemeja lengan pendek pria formal slim fit navy houseofcuff',299000,'House of Cuff',4.5,0);
INSERT INTO "df" VALUES('Seersucker Short Sleeve Shirt',329900,'Executive',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Tencel Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('Lawell Kemeja Pria Lengan Pendek Kotak-Kotak Regular Fit warna White â€“ GARNET',349000,'Lawell',5.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHG Brandon S/s White',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Lawell Baju Koko Pria Lengan Pendek Bordir Modern Fit Warna Grey â€“ LAQKFSBKQG101QCTNQNM',389000,'Lawell',4.7,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Lengan Panjang Katun Denim Biru 76422',549000,'Platini',4.9,0);
INSERT INTO "df" VALUES('[NEW] Osella Wesley Regular Fit Long Sleeve Shirt 20374016 | Kemeja Lengan Panjang Pria',449900,'Osella',5.0,0);
INSERT INTO "df" VALUES('OXCON Easy Shirts Kemeja Tangan Pendek Light Grey',255000,'Oxcon',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Pendek Polinosic Twill Putih 63243',479000,'Platini',4.8,0);
INSERT INTO "df" VALUES('Manzone Kemeja Lengan Pendek Pria Rodrick 3 Slim Fit - Navy',179900,'Manzone',4.9,0);
INSERT INTO "df" VALUES('MSH BARACOSTONE WHT',765000,'Volcom',4.9,1);
INSERT INTO "df" VALUES('Platini Kemeja Lengan Panjang Katun Motif Kotak Navy 76461',549000,'Platini',4.9,1);
INSERT INTO "df" VALUES('MSH BECKETT OXFORD 2 SHORT SLEEVE SHIRT BLACK',765000,'Volcom',5.0,0);
INSERT INTO "df" VALUES('Cotton Well Oman Henley Shirt Coffeeâ”‚Kemeja Koko Basic Lengan Panjang Coklat Tua Kopi',299000,'Cotton Well',5.0,0);
INSERT INTO "df" VALUES('Kemeja Tangan Pendek',519000,'Andrew Smith',NULL,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Regular Fit Pria',399000,'Police Denim',4.9,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Regular Fit Lengan Panjang Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Abu Regular Fit Pria',399000,'Police Denim',4.8,1);
INSERT INTO "df" VALUES('Schoeller Baju Koko Pria Lengan Panjang Warna Blue | SHQKCLKKQO102QCTNQNM',349000,'Schoeller',4.0,0);
INSERT INTO "df" VALUES('Greenlight Voyager Men''s Shirt Short Sleeve Regular Fit Cotton Atha C081124',219000,'GREENLIGHT',4.8,1);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford COKLAT MUDA 1069',299000,'Platini',4.8,1);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Basic Cotton Soft Grey Regular Fit Lengan Panjang Pria',399000,'Police Denim',4.9,0);
INSERT INTO "df" VALUES('AMK Kemeja Batik Pria Lengan Panjang SHB Banjarejo Ls Olive',469000,'AMK',5.0,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Panjang Pria DUNSTON-KHAKI',399900,'MOC',4.5,0);
INSERT INTO "df" VALUES('Cotton Well Ben Short Sleeve Oxford Shirt Peanut Brown | Kemeja Pria Lengan Pendek Basic Polos Coklat ',279000,'Cotton Well',4.8,0);
INSERT INTO "df" VALUES('Cotton Well Oman Henley Shirt Soft Sage â”‚Kemeja Koko Basic Lengan Panjang Hijau Sage Muda',299000,'Cotton Well',4.9,0);
INSERT INTO "df" VALUES('Easy Iron Pure Cotton Oxford Shirt',649900,'Marks & Spencer',5.0,1);
INSERT INTO "df" VALUES('POLICE Kemeja Kotak Yarndyed Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('Pure Linen Shirt',1099900,'Marks & Spencer',4.9,1);
INSERT INTO "df" VALUES('MAGINOT OXFORD 2.0 BLUE Kemeja Casual Slim Fit Lengan Panjang',499000,'Maginot',4.7,1);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Panjang SHS CHIKO L/S Navy',469000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Motif Lengan Pendek Biru 132040',479000,'Platini',4.9,0);
INSERT INTO "df" VALUES('OXCON Kemeja koko Tangan 3/4 Bordir Hasbi Hitam',245000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Panjang Katun Oxford Putih 11069',320000,'Platini',4.8,0);
INSERT INTO "df" VALUES('POLICE Kemeja Yarndyed Kotak Regular Fit Pria - Tersedia Big Size',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Kantong Dua Regular Fit Pria',399000,'Police Denim',NULL,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Regular Fit Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Flanel Pria Lengan Panjang Katun 76496',599000,'Platini',4.9,0);
INSERT INTO "df" VALUES('Crocodile MALE 0129 Black 05 - Men Shirt Kemeja Lengan Pendek - Relax Fit - Katun',559000,'Crocodile',4.9,0);
INSERT INTO "df" VALUES('Linen Blend Slim Fit Shirt - Navy LS',499000,'VENGOZ',4.6,0);
INSERT INTO "df" VALUES('Schoeller Kemeja Pria Lengan Panjang Polos Warna Maroon â€“ S.9-KCLSF-O101-CTN',349000,'Schoeller',5.0,0);
INSERT INTO "df" VALUES('OXCON Kemeja koko Tangan Panjang Collarless Azfar Mid Grey',225000,'Oxcon',4.8,0);
INSERT INTO "df" VALUES('Finn',559000,'Obermain',5.0,1);
INSERT INTO "df" VALUES('LGS - Slim Fit - Kemeja Casual - Grey - Motif - JSH.391.S757F.572.C',397800,'LGS',5.0,0);
INSERT INTO "df" VALUES('Ray Outer Shirt',559000,'Obermain',5.0,1);
INSERT INTO "df" VALUES('Greggory Shirts',449900,'X-EIGHT',4.9,1);
INSERT INTO "df" VALUES('POLICE Kemeja Abstrak Printing Cotton Soft Yellow Blue Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Kantong Dua Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('MOC - Kemeja Kotak-kotak Lengan Pendek Pria Zertta - Navy',329900,'MOC',NULL,0);
INSERT INTO "df" VALUES('Long Sleeve Flanel Checks Shirt',429900,'WOOD',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Abstrak Printing Hitam Regular Fit Pria',399000,'Police Denim',4.9,1);
INSERT INTO "df" VALUES('LGS - Kemeja - Slim fit - Motif - kotak Kotak - JSH.390.S727F.542.C',389800,'LGS',NULL,0);
INSERT INTO "df" VALUES('Fazwan Shirts',469900,'X-EIGHT',5.0,0);
INSERT INTO "df" VALUES('MEN''S NAVY BLUE OXFORD LONG SLEEVE REGULAR SHIRT',399900,'VALINO',4.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Lengan Pendek Basic katun oxford Cream  63213',479000,'Platini',4.8,1);
INSERT INTO "df" VALUES('Platini Kemeja Pria Motif Kotak Lengan Panjang Khaki 72007.28',599000,'Platini',5.0,0);
INSERT INTO "df" VALUES('Gloaming Kemeja Flanel Veterano Unisex Panjang Bravion',320000,'Gloaming',5.0,0);
INSERT INTO "df" VALUES('Caspian Vertical Stripe Pattern Shirt',599000,'Obermain',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Putih Pria Lengan Pendek Basic Katun Oxford  63200',479000,'Platini',4.8,0);
INSERT INTO "df" VALUES('Cotton Well Elvon Smart Shirt White | Kemeja Pria Formal Basic Clean Lengan Panjang Putih',399000,'Cotton Well',5.0,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Pendek Pria Briscoe - Khaki',279900,'MOC',4.9,0);
INSERT INTO "df" VALUES('MOC Kemeja Batik Lengan Pendek Pria KRADEV - WHITE',359900,'MOC',4.9,0);
INSERT INTO "df" VALUES('OXCON Easy Shirts Kemeja Tangan Pendek Navy',255000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('Easy Iron Pure Linen Shirt',849900,'Marks & Spencer',5.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS Jiya Ss Cream',549000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Manzone Kemeja Lengan Panjang Pria Slim Fit Foxy - Light Blue',179900,'Manzone',4.9,0);
INSERT INTO "df" VALUES('BASTIEN - BEIGE WHITE PEPPER Kemeja Flannel Casual Pria Lengan Panjang LS - Top Man Shirt',499900,'Edwin Jeans',4.9,1);
INSERT INTO "df" VALUES('Short Sleeve Micro Check Shirt',399900,'WOOD',4.9,1);
INSERT INTO "df" VALUES('MAGINOT Kemeja Pria Basic Panjang DARK PURPLE',499000,'Maginot',4.8,0);
INSERT INTO "df" VALUES('AMK Kemeja Polos Pria Oversize Lengan Panjang SHS Fargo Ls Camel',469000,'AMK',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Basic Cotton Soft Choco Brown Regular Fit Lengan Panjang Pria',399000,'Police Denim',4.9,1);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford Putih 1069',299000,'Platini',4.9,0);
INSERT INTO "df" VALUES('OXCON Kemeja Koko Pria Lengan Panjang Polos Fitra Cream',255000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('GREEN LONG SLEEVE SHIRT FOR MEN',459900,'VALINO',3.7,0);
INSERT INTO "df" VALUES('RBJ Kemeja Polos Cotton Slub Krah Hawaii Black Regular Fit Pria',399000,'RBJ',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Coklat Regular Fit Pria',399000,'Police Denim',4.8,1);
INSERT INTO "df" VALUES('Dark Beige Cotton Twill Premium Shirt LS',399000,'VENGOZ',4.8,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Panjang SHS ANDREW L/S Light Blue',469000,'AMK',4.8,0);
INSERT INTO "df" VALUES('JIRO - WHITE Kemeja Lengan Panjang Pria Top Man Shirt Warna White',499900,'Edwin Jeans',4.8,1);
INSERT INTO "df" VALUES('Jobb Pitsea Kemeja Pria Lengan Pendek Slim Fit Dark Navy',559000,'Jobb',5.0,0);
INSERT INTO "df" VALUES('Akarasya Hitam Kemeja Batik Pria Premium Slimfit Lengan Pendek NLN',359000,'ABIROY',4.5,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Panjang SHS Yonas Ls Olive',569000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Kemeja Putih Pria Slim Fit Motif Micro Dobby Schoeller Lengan Panjang | DORMA-MLNS-PT',549000,'Schoeller',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Regular Fit Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Panjang Polinosic Twill Hitam 66243',499000,'Platini',4.9,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Jeans  Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('BASTIEN - BLACK GREY Kemeja Flannel Casual Pria Lengan Panjang LS - Top Man Shirt',499900,'Edwin Jeans',5.0,1);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Panjang Polinosic Twill Putih 66243',499000,'Platini',4.8,0);
INSERT INTO "df" VALUES('Hugo Stripe Shirt Brown LS',399000,'VENGOZ',4.8,0);
INSERT INTO "df" VALUES('OXCON Kemeja koko Tangan Panjang Collarless Azfar Navy',225000,'Oxcon',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Kotak Pria Lengan Pendek Katun Red Navy 73622 ',399000,'Platini',4.5,1);
INSERT INTO "df" VALUES('CCSL Kemeja Cotton',569000,'Cardinal',5.0,0);
INSERT INTO "df" VALUES('Paulmay Kemeja Pria Reguler Fit White Shirt',199000,'PAULMAY',4.7,0);
INSERT INTO "df" VALUES('MOC - Kemeja Motif Lengan Pendek Pria Owen - White',279900,'MOC',4.8,0);
INSERT INTO "df" VALUES('Dwan Atasan Kemeja Pria Three Lines Slim Fit Casual Shortsleeve Shirt Material Cotton ORIGINAL - Navy',1312500,'Hamlin',4.8,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Panjang Pria DEACON-LIGHT BROWN',399900,'MOC',4.9,0);
INSERT INTO "df" VALUES('Viscose Red Wine Casual Shirt',359000,'VENGOZ',4.7,0);
INSERT INTO "df" VALUES('Pure Cotton Oxford Shirt',649900,'Marks & Spencer',4.9,1);
INSERT INTO "df" VALUES('ELMO GREEN OLIVE Kemeja Lengan Panjang Pria - Top Man Shirt',459900,'Edwin Jeans',4.5,0);
INSERT INTO "df" VALUES('Luca Kemeja Pendek Pria Katun Organik Mint | Organic Cotton Short Sleeves Shirt Men Mint',299000,'Remedy',4.7,0);
INSERT INTO "df" VALUES('Cotton Well Morocco Shirt Black â”‚Kemeja Koko Pria Kerah V Neck Hitam',279000,'Cotton Well',4.9,0);
INSERT INTO "df" VALUES('Johnwin - Kemeja Lengan Panjang - Navy - Motif - ASH.670.S871.740.C-L/S - Free Keychain',354600,'Johnwin',5.0,0);
INSERT INTO "df" VALUES('OXCON Extra Comfort Authentic Flannel Shirt Turqoise Cream',370000,'Oxcon',4.9,0);
INSERT INTO "df" VALUES('Kemeja koko Collarless shirt OXCON GHAISAN Bronze',245000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Motif Pria Lengan Pendek SHP Dalton Ss Blue',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('OXCON Kemeja koko Tangan 3/4 Bordir Hasbi Cream',245000,'Oxcon',4.7,0);
INSERT INTO "df" VALUES('Cotton Dobby Cheked Shirt KLS604',469500,'Lois Jeans',5.0,1);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS ITO S/S Light Blue',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Motif Kotak Lengan Panjang 76606',399000,'Platini',4.9,0);
INSERT INTO "df" VALUES('OXCON Kemeja koko Tangan Panjang Collarless Azfar Teracotta',225000,'Oxcon',4.8,0);
INSERT INTO "df" VALUES('Eaden Stand Collar Shirt',699000,'Obermain',5.0,0);
INSERT INTO "df" VALUES('MEN''S NAVY LONG SLEEVE SHIRT',399900,'VALINO',5.0,0);
INSERT INTO "df" VALUES('Platini Baju Kemeja Polos Basic Pria Pendek Polinosic Hitam 63100',479000,'Platini',4.9,0);
INSERT INTO "df" VALUES('Kemeja Flanel Panjang Martens Unisex',290000,'Gloaming',4.8,1);
INSERT INTO "df" VALUES('OXCON Kemeja collarless kerah koko Suede Kasual Pria Lengan Pendek Maroon',235000,'Oxcon',4.7,0);
INSERT INTO "df" VALUES('Platini Kemeja Shanghai Lengan Panjang Katun Oxford Slub Sky Blue 961056',499000,'Platini',5.0,0);
INSERT INTO "df" VALUES('MOC Kemeja Batik Shanghai Lengan Panjang Pria SORLEY-NAVY',459900,'MOC',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Olive Regular Fit Pria',399000,'Police Denim',4.9,1);
INSERT INTO "df" VALUES('MOC Kemeja Motif Lengan Panjang Pria Mateo - Dark Green',299900,'MOC',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Cream Coklat Regular Fit Pria',399000,'Police Denim',4.7,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Basic Cotton Soft Regular Fit Lengan Pendek Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Batik Pria Lengan Panjang Katun Maroon 36051',548998,'Platini',5.0,0);
INSERT INTO "df" VALUES('Cotton Well Oman Henley Shirt Whiteâ”‚Kemeja Koko Basic Lengan Panjang Putih',299000,'Cotton Well',5.0,0);
INSERT INTO "df" VALUES('Manzone Kemeja Lengan Panjang Pria Slim Fit Foxy - Beige',179900,'Manzone',4.7,0);
INSERT INTO "df" VALUES('MANZONE - Kemeja Lengan Pendek Pria Domeria 02 Comfort Fit - Light Blue Warna Blue_Light',259900,'Manzone',NULL,0);
INSERT INTO "df" VALUES('Dead Flower Shirt',649000,'Blood & Bone',4.9,0);
INSERT INTO "df" VALUES('MANZONE - Kemeja Batik Lengan Pendek Pria Astagira Modern Fit - Black',299900,'Manzone',4.9,0);
INSERT INTO "df" VALUES('Worn Cortans Kemeja Pendek Black',290000,'Gloaming',4.8,0);
INSERT INTO "df" VALUES('Adipati Shirts',469900,'X-EIGHT',5.0,0);
INSERT INTO "df" VALUES('Levi''sÂ® Men''s Authentic Button-Down Shirt (A7210-0030)',699900,'Levi''s',4.9,0);
INSERT INTO "df" VALUES('Cotton Well Morocco Shirt Latte | Kemeja Koko Pria Kerah V Neck Coklat Susu',279000,'Cotton Well',5.0,0);
INSERT INTO "df" VALUES('Paulmay Kemeja Pria Reguler Fit Black Shirt',199000,'PAULMAY',4.7,0);
INSERT INTO "df" VALUES('Platini Kemeja Motif Kotak Pria Lengan Pendek Katun RED 71008',549000,'Platini',5.0,0);
INSERT INTO "df" VALUES('[NEW] Osella Soetta Long Sleeve Shirt 20374013 | Kemeja Lengan Panjang Pria',549900,'Osella',NULL,0);
INSERT INTO "df" VALUES('OXCON Easy Shirts Kemeja Tangan Pendek Army',255000,'Oxcon',4.9,0);
INSERT INTO "df" VALUES('Easy Iron Pure Cotton Striped Shirt',799900,'Marks & Spencer',5.0,1);
INSERT INTO "df" VALUES('Platini Kemeja Motif Pria Lengan Pendek Hitam 132207',499000,'Platini',4.8,0);
INSERT INTO "df" VALUES('Matsuda Kemeja Pria Lengan pendek Waffle Kasual Sagae',349000,'Matsuda',4.9,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHP Eloah S/S Navy Blue',449000,'AMK',4.9,0);
INSERT INTO "df" VALUES('MOC - Kemeja Batik Pria Lengan Panjang Balereng - White Warna White',379900,'MOC',5.0,1);
INSERT INTO "df" VALUES('Linen Blend Slim Fit Shirt - White LS',499000,'VENGOZ',4.6,1);
INSERT INTO "df" VALUES('Regular Fit Short Sleeve Twill Shirt',399900,'WOOD',5.0,0);
INSERT INTO "df" VALUES('Kemeja Tangan Pendek',479000,'Andrew Smith',NULL,0);
INSERT INTO "df" VALUES('(Special Price) Platini Kemeja Motif Salur Pria Lengan Pendek 131990',479000,'Platini',4.6,0);
INSERT INTO "df" VALUES('RBJ Kemeja Polos Cotton Slub Putih Regular Fit Big Size',399000,'RBJ',5.0,0);
INSERT INTO "df" VALUES('BLACK SHORT-SLEEVED SHIRT FOR MEN',199900,'VALINO',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Kotak Cotton Abu Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('Kemeja koko Collarless shirt OXCON GHAISAN Dark Grey',245000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('Greenlight Men''s Shirt Short Sleeve Regular Fit Cotton Full Print Blaire HP-C020525',219000,'GREENLIGHT',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Motif Print Pria Lengan Pendek Katun Putih 73376',579000,'Platini',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Motif Salur Pria Lengan Pendek Katun Oxford Biru 73272',499000,'Platini',4.9,0);
INSERT INTO "df" VALUES('Moutley Men''s Shirt Short Sleeve Oversized Fit Cotton Shoko OL-C020125',329000,'GREENLIGHT',NULL,0);
INSERT INTO "df" VALUES('POLICE Kemeja Salur Printing Regular Fit Pria',399000,'Police Denim',4.5,0);
INSERT INTO "df" VALUES('POLICE Kemeja Abstrak Printing Navy Regular Fit Pria',399000,'Police Denim',4.9,1);
INSERT INTO "df" VALUES('Regular Fit Cotton Blend Short Sleeve Shirt',849900,'Marks & Spencer',5.0,0);
INSERT INTO "df" VALUES('Kemeja Collarless Slub koko biru navy OXCON Navy blue',225000,'Oxcon',4.8,0);
INSERT INTO "df" VALUES('Greenlight Men''s Basic Shirt Short Sleeve Regular Fit Mandarin Collar Leandro HP-C040125',229000,'GREENLIGHT',NULL,0);
INSERT INTO "df" VALUES('Kemeja Tangan Pendek',589000,'Andrew Smith',NULL,0);
INSERT INTO "df" VALUES('Lawell Baju Koko Pria Lengan Pendek Bordir Modern Fit Warna Cream â€“ LAQKFSBKQG101QCTNQNM',389000,'Lawell',5.0,0);
INSERT INTO "df" VALUES('Lawell Kemeja Casual Pria Lengan Pendek Regular Fit Warna Green â€“ Cotton Oxford Kecil â€“ KING-MSRC',349000,'Lawell',5.0,0);
INSERT INTO "df" VALUES('Relaxed Fit Short Sleeve Textured Shirt',329900,'Executive',4.9,0);
INSERT INTO "df" VALUES('Waffle Overshirt',1199900,'Marks & Spencer',5.0,1);
INSERT INTO "df" VALUES('Galunggung Ijo Kemeja Batik Pria Premium Slimfit Modern Lengan Panjang',650000,'Batik Mayung',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Batik Pria Lengan Panjang Katun Navy Abu 36026',549000,'Platini',4.8,0);
INSERT INTO "df" VALUES('Kemeja Lengan Panjang Modern Pierre Cardin Solid Nomad - Cream Festive Look',1998000,'Pierre Cardin',3.0,0);
INSERT INTO "df" VALUES('Relaxed Fit Short Sleeve Stripes Shirt',399900,'WOOD',5.0,0);
INSERT INTO "df" VALUES('Pure Cotton Oxford Shirt',949900,'Marks & Spencer',NULL,0);
INSERT INTO "df" VALUES('MOC - Kemeja Batik Pria Lengan Panjang Nurras - Blue',379900,'MOC',4.8,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Panjang Pria LOURY - BEIGE',399900,'MOC',4.5,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Pendek Pria MONTE - DARK GREY',359900,'MOC',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Cotton Kantong Dua Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('MEN''S BLUE LONG SLEEVE SHIRT',429900,'VALINO',5.0,0);
INSERT INTO "df" VALUES('Kemeja Polos Slimfit Formal',369000,'Cardinal',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Lengan Pendek Basic katun oxford Navy 63212',479000,'Platini',4.9,0);
INSERT INTO "df" VALUES('Schoeller Kemeja Formal Pria Lengan Pendek â€“ Navy â€“ Slim Fit | Artikel MSNS',349000,'Schoeller',5.0,0);
INSERT INTO "df" VALUES('Regular Fit Short Sleeve Oxford Shirt',399900,'WOOD',5.0,1);
INSERT INTO "df" VALUES('POLICE Kemeja Kotak Cotton Slub Biru Regular Fit Pria',399000,'Police Denim',4.7,0);
INSERT INTO "df" VALUES('POLICE Kemeja Abstrak Printing Cotton Soft Coklat Regular Fit Pria',399000,'Police Denim',4.7,0);
INSERT INTO "df" VALUES('Relaxed Fit Knitted Striped Shirt',1099900,'Marks & Spencer',5.0,1);
INSERT INTO "df" VALUES('Platini Kemeja Motif Pria Lengan Pendek Putih 132158',479000,'Platini',4.9,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS Eiffel Ss White',449000,'AMK',NULL,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHP Aris S/S Red',449000,'AMK',NULL,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Corak Herringbone Regular Fit Pria',399000,'Police Denim',NULL,0);
INSERT INTO "df" VALUES('MANZONE Kemeja Lengan Panjang Pria MZY-SAND - GREY',359900,'Manzone',5.0,0);
INSERT INTO "df" VALUES('Regular Fit Cotton Rich Striped Shirt',849900,'Marks & Spencer',5.0,0);
INSERT INTO "df" VALUES('Kemeja lengan pendek pria formal slim fit black houseofcuff',299000,'House of Cuff',4.5,1);
INSERT INTO "df" VALUES('Manzone Kemeja Lengan Panjang Pria Philsvir 05 - Brown',249900,'Manzone',4.6,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS Jiya Ss Olive',549000,'AMK',5.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHP Diego S/S Olive',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Twill Slub Off White Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Logo Plat Besi Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Batik Pria Lengan Panjang Katun Hitam 36035',549000,'Platini',4.8,0);
INSERT INTO "df" VALUES('Kemeja Tangan Panjang',519000,'Andrew Smith',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Relaxfit Cotton Slub Maroon Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Motif Kotak Lengan Panjang White 76603.07',399000,'Platini',5.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS Jiya Ss Camel',549000,'AMK',NULL,0);
INSERT INTO "df" VALUES('OXCON Kemeja collarless kerah koko Suede Kasual Pria Lengan Pendek Navy',235000,'Oxcon',4.7,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria  Lengan Panjang SHG Ringga L/S Grey',469000,'AMK',NULL,0);
INSERT INTO "df" VALUES('AMK Kemeja Polos Oversize Pria Lengan Panjang SHS Nelson Ls Dark Grey',469000,'AMK',NULL,0);
INSERT INTO "df" VALUES('POLICE Kemeja Yarndyed Kotak Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('Kemeja Pria Oxford Lengan Panjang - White',400000,'Enzy Batik',4.7,0);
INSERT INTO "df" VALUES('Mahesintra Putih Kemeja Batik Pria Premium Slimfit Lengan Pendek NLN',359000,'ABIROY',3.8,1);
INSERT INTO "df" VALUES('Houseofcuff Kemeja Lengan Panjang Pria Formal Slim Fit Putih',250000,'House of Cuff',4.4,0);
INSERT INTO "df" VALUES('Pure Cotton Textured Shirt',849900,'Marks & Spencer',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Motif Salur Pria Lengan Pendek Katun Cream 73492',519000,'Platini',5.0,0);
INSERT INTO "df" VALUES('Cotton Well Elvon Smart Shirt Light Blue | Kemeja Pria Formal Basic Clean Lengan Panjang Biru Muda',399000,'Cotton Well',5.0,0);
INSERT INTO "df" VALUES('MOC Kemeja Batik Lengan Pendek Pria SHARABHA-NAVY',359900,'MOC',5.0,0);
INSERT INTO "df" VALUES('Leopold Kemeja Koko Pria Lengan Pendek Motif Bordir Material Cotton ORIGINAL - Black',847500,'Hamlin',5.0,0);
INSERT INTO "df" VALUES('Pl Mando Sss',699000,'Hush Puppies',5.0,1);
INSERT INTO "df" VALUES('Kemeja Tangan Pendek',489000,'Andrew Smith',NULL,0);
INSERT INTO "df" VALUES('OXCON Kemeja koko Tangan Panjang Collarless Azfar Hitam',225000,'Oxcon',4.8,0);
INSERT INTO "df" VALUES('Aksaja Shirts',449900,'X-EIGHT',4.3,0);
INSERT INTO "df" VALUES('Gloaming Kemeja Flanel Veterano Unisex Panjang Delecta',320000,'Gloaming',4.8,1);
INSERT INTO "df" VALUES('Lawell Baju Koko Pria Polos Lengan Panjang Slim Fit Warna Beige | ESPRIT',349000,'Lawell',4.5,0);
INSERT INTO "df" VALUES('MANZONE - Kemeja Lengan Pendek Pria Maliq 1 Modern Fit - Dark Grey Warna Grey_Dark',259900,'Manzone',NULL,0);
INSERT INTO "df" VALUES('Classic Shirt',759000,'Trendyol',NULL,0);
INSERT INTO "df" VALUES('Regular Fit Pure Linen Shirt',1099900,'Marks & Spencer',5.0,1);
INSERT INTO "df" VALUES('Cotton Well Oman Henley Shirt Blue â”‚Kemeja Koko Basic Lengan Panjang Biru',299000,'Cotton Well',4.9,0);
INSERT INTO "df" VALUES('Kemeja koko Collarless shirt OXCON GHAISAN Light Blue',245000,'Oxcon',4.6,0);
INSERT INTO "df" VALUES('Kemeja Flanel Panjang Biturate Sant Unisex',290000,'Gloaming',4.8,0);
INSERT INTO "df" VALUES('Kemeja Katun Lengan Pendek Hitam Motif Kotak-Kotak 16885',389000,'Andre Michel',NULL,0);
INSERT INTO "df" VALUES('MEN''S WHITE CHECKERED SHORT SLEEVE SHIRT',599900,'Arnold Palmer',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Motif Kotak Lengan Panjang Black 76603.04',399000,'Platini',3.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Batik Pria Lengan Pendek SHB Beringin Ss Black',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Flannel Plaid Shirt',759000,'Trendyol',4.8,0);
INSERT INTO "df" VALUES('Leopard Print S/S Shirt',900000,'Denim Project',NULL,0);
INSERT INTO "df" VALUES('Jobb Brioni Kemeja Pria Lengan Panjang Regular Fit Navy',559000,'Jobb',4.7,0);
INSERT INTO "df" VALUES('MOC - Kemeja Motif Pria Lengan Pendek Nirved - Olive Light',259900,'MOC',5.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHP Bern S/S Black',449000,'AMK',4.0,0);
INSERT INTO "df" VALUES('Regular Fit Long Sleeve Checks Shirt',429900,'WOOD',4.7,0);
INSERT INTO "df" VALUES('Cordarious Shirts',449900,'X-EIGHT',5.0,0);
INSERT INTO "df" VALUES('CJ Kemeja Slim Fit',469000,'Cardinal',5.0,0);
INSERT INTO "df" VALUES('Caspian Vertical Stripe Pattern Shirt',599000,'Obermain',4.8,0);
INSERT INTO "df" VALUES('Jayko',599000,'Hush Puppies',4.6,1);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS Gerald Ss Dark Olive',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Space Blue Denim Shirt LS',699000,'VENGOZ',5.0,0);
INSERT INTO "df" VALUES('Podium',599000,'Hush Puppies',5.0,0);
INSERT INTO "df" VALUES('Greenlight Men''s Shirt Short Sleeve Regular Fit Cotton Poplin Full Print Jean HP-C011125',229000,'GREENLIGHT',NULL,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS Andreas Ss Olive',449000,'AMK',NULL,0);
INSERT INTO "df" VALUES('MEN''S GREEN PLAID SHORT SLEEVE SHIRT',599900,'Arnold Palmer',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Corak Herringbone Regular Fit Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('OXCON Kemeja koko Tangan 3/4 Bordir Hasbi Maroon',245000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('Leopold Kemeja Printing Pria Motif Abstrak Lengan Pendek Material Rayon ORIGINAL - Black',1422500,'Hamlin',4.3,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Pendek Pria HUGOS - NAVY',259900,'MOC',5.0,0);
INSERT INTO "df" VALUES('Cotton Well Light Denim Series in Washed Blue | Kemeja Lengan Panjang Denim Biru',329000,'Cotton Well',4.8,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS Gerald Ss Khaki',449000,'AMK',NULL,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHP Jenewa S/S Blue',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Hawai Pria Lengan Pendek Coklat 132106',479000,'Platini',4.8,0);
INSERT INTO "df" VALUES('AMK Kemeja Batik Pria Lengan Panjang SHB Kundjang Ls Black',469000,'AMK',NULL,0);
INSERT INTO "df" VALUES('OXCON Kemeja collarless kerah koko Suede Kasual Pria Lengan Pendek Khakis',235000,'Oxcon',4.7,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Relaxfit Cotton Slub Abu Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford Salem 1069',299000,'Platini',4.9,0);
INSERT INTO "df" VALUES('MOC - Kemeja Shanghai Lengan Panjang Pria Farazz - Black',469900,'MOC',4.7,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHP Aero S/S Cream',449000,'AMK',2.0,0);
INSERT INTO "df" VALUES('Super White Oxford SS Shirt',359000,'VENGOZ',4.6,0);
INSERT INTO "df" VALUES('OXCON Kemeja koko Tangan 3/4 Bordir Hasbi Mid Grey',245000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('Cotton Rich Seersucker Check Shirt',849900,'Marks & Spencer',NULL,1);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS YIRUMA S/S Premiere Solid Coklat Tua',449000,'AMK',3.0,0);
INSERT INTO "df" VALUES('Lawell Kemeja Pria Lengan Pendek Kotak-Kotak Regular Fit â€“ Caesar',349000,'Lawell',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Twill Slub Tan Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHP Cairo S/S Green',449000,'AMK',4.2,0);
INSERT INTO "df" VALUES('Schoeller Kemeja Pria Lengan Pendek Slim Fit Motif Garis Warna Maroon â€“Tiago',349000,'Schoeller',NULL,0);
INSERT INTO "df" VALUES('Lawell Kemeja Pria Lengan Panjang Kotak-Kotak Regular Fit Warna Navy - RAFA-MLRF',399000,'Lawell',5.0,0);
INSERT INTO "df" VALUES('MANZONE X Merry Riana - Kemeja Lengan Panjang Pria Crown Modern Fit - White Warna White',299900,'Manzone',4.8,0);
INSERT INTO "df" VALUES('Johnwin - Slim Fit - Kemeja Formal Pria - Hitam - Lengan Pendek - FSH.650.K392.875.C-S/S',409600,'Johnwin',5.0,0);
INSERT INTO "df" VALUES('MANZONE - Kemeja Lengan Panjang Pria Jasper Modern Fit - Navy Warna Navy',359900,'Manzone',4.8,0);
INSERT INTO "df" VALUES('OXCON Extra Comfort Authentic Flannel Shirt Navy Brown White',370000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('Kemeja Lengan Panjang Ethan White Deep Grove - Dark Green Casual',796000,'ETHAN WHITE',5.0,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Basic Cotton Soft Rose Gold Regular Fit Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('AMK Kemeja Motif Pria Lengan Pendek SHP Davao Ss Black',449000,'AMK',NULL,0);
INSERT INTO "df" VALUES('AMK Kemeja Polos Pria Lengan Pendek SHS Jackson Ss Navy Blue',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('OXCON Kemeja Tangan Panjang Koko Knit Malik Collarless Shirt Mocca',235000,'Oxcon',5.0,0);
INSERT INTO "df" VALUES('Cotton Dobby Shirt KLL602',479500,'Lois Jeans',5.0,1);
INSERT INTO "df" VALUES('Hector Plaid Shirt Stone Blue LS',399000,'VENGOZ',4.8,0);
INSERT INTO "df" VALUES('LGS - Slim Fit - Kemeja Fashion - Corak Gradasi Warna - biru',397800,'LGS',5.0,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHS Jiya Ss Blue',549000,'AMK',NULL,0);
INSERT INTO "df" VALUES('Giordano Men''s Poplin Shirt 0104500201',699000,'Giordano',5.0,1);
INSERT INTO "df" VALUES('AMK Kemeja Batik Pria Lengan Pendek SHB Jelani Ss Blue',449000,'AMK',NULL,0);
INSERT INTO "df" VALUES('LS Pure Cotton Printed Oxford Shirt',699900,'Marks & Spencer',4.7,0);
INSERT INTO "df" VALUES('Virgo Stripe Shirt Grey SS',389000,'VENGOZ',4.6,0);
INSERT INTO "df" VALUES('Dwan Shirt Kemeja Jeans Sandwash Pria Kasual Lengan Panjang Material Denim ORIGINAL - Sandwash Blue',1982500,'Hamlin',4.5,0);
INSERT INTO "df" VALUES('Dwan Casual Shirt Kemeja Polos Pria Lengan Pendek Kasual Formal Material Cotton ORIGINAL - Blue',832500,'Hamlin',5.0,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Pendek Pria ASFA - BLACK Colour BLACK',459900,'MOC',4.9,0);
INSERT INTO "df" VALUES('Checked Overshirt',1099900,'Marks & Spencer',5.0,1);
INSERT INTO "df" VALUES('Hugo Stripe Shirt White LS',399000,'VENGOZ',4.8,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Slim Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('Platini Kemeja Motif Pria Lengan Pendek 71010',399000,'Platini',5.0,0);
INSERT INTO "df" VALUES('Lawell Baju Koko Pria Polos Lengan Panjang Slim Fit Warna Army | ESPRIT',349000,'Lawell',5.0,0);
INSERT INTO "df" VALUES('Pure Linen Grandad Collar Shirt',1099900,'Marks & Spencer',5.0,1);
INSERT INTO "df" VALUES('Cotton Well Elvon Smart Shirt Navy | Kemeja Pria Formal Basic Clean Lengan Pendek Biru Donker Tua',358999,'Cotton Well',5.0,0);
INSERT INTO "df" VALUES('Worn Cortans Kemeja Pendek Army',290000,'Gloaming',4.8,0);
INSERT INTO "df" VALUES('POLICE Kemeja Printing Cotton Soft Coklat Regular Fit Pria',399000,'Police Denim',4.8,0);
INSERT INTO "df" VALUES('POLICE Kemeja Salur Printing Regular Fit Pria',399000,'Police Denim',5.0,1);
INSERT INTO "df" VALUES('Platini Kemeja Pria Flanel Panjang Maroon 76302',599000,'Platini',4.8,0);
INSERT INTO "df" VALUES('AMK LAKSANA BLACK',449000,'AMK',5.0,0);
INSERT INTO "df" VALUES('Johnwin - Slim Fit - Kemeja Casual Active - Lengan Abu - Putih',332600,'Johnwin',4.6,0);
INSERT INTO "df" VALUES('POLICE Kemeja Abstrak Printing Cotton Soft Abu Regular Fit Pria',399000,'Police Denim',4.7,0);
INSERT INTO "df" VALUES('POLICE Kemeja Polos Cotton Biru Tua Regular Fit Pria',399000,'Police Denim',5.0,0);
INSERT INTO "df" VALUES('MANZONE - Kemeja Dobby Lengan Pendek Pria Larry Comfort Fit - Grey Warna Grey',279900,'Manzone',5.0,0);
INSERT INTO "df" VALUES('Johnwin - Kemeja Casual - Polos - Coklat - SlimFit - ASH.670.K880.820',343600,'Johnwin',5.0,0);
INSERT INTO "df" VALUES('Lawell Kemeja Pria Polos Lengan Pendek Regular Fit â€“ DESMOND-MSRF-GRN | Green | Easy Care Wrinkle Resistant',299000,'Lawell',NULL,0);
INSERT INTO "df" VALUES('MEN''S BLUE SLIM FIT LONG SLEEVE SHIRT',429900,'VALINO',NULL,0);
INSERT INTO "df" VALUES('OXCON Kemeja Tangan Panjang Koko Knit Malik Collarless Shirt Dark Brown',235000,'Oxcon',NULL,0);
INSERT INTO "df" VALUES('Platini Baju Kemeja Pria Lengan Panjang Polos Polinosic Hitam 66100',499000,'Platini',4.9,1);
INSERT INTO "df" VALUES('K-CLUB SHIRT YELLOW',699000,'Blood & Bone',4.9,1);
INSERT INTO "df" VALUES('MANZONE - Kemeja Lengan Pendek Pria Olav Modern Fit - Grey Warna Grey',259900,'Manzone',NULL,0);
INSERT INTO "df" VALUES('Anggara Shirts',469900,'X-EIGHT',5.0,0);
INSERT INTO "df" VALUES('Cotton Rich Seersucker Shirt',799900,'Marks & Spencer',5.0,0);
INSERT INTO "df" VALUES('Worn Cortans Dark Kemeja Panjang Brown',300000,'Gloaming',5.0,0);
INSERT INTO "df" VALUES('Pluto',599000,'Hush Puppies',5.0,0);
INSERT INTO "df" VALUES('(Special Price) Platini Kemeja Motif Pria Lengan Pendek 132266',369000,'Platini',5.0,0);
INSERT INTO "df" VALUES('Crocodile MALE 0129 Blue 14 - Men Shirt Kemeja Lengan Pendek - Relax Fit - Katun',559000,'Crocodile',4.9,0);
INSERT INTO "df" VALUES('MOC Kemeja Lengan Panjang Stripes Pria Myles - Teal',299900,'MOC',5.0,0);
INSERT INTO "df" VALUES('GANT - Pakaian Pria - Reg Oxford Shirt - White',1799000,'Gant',4.8,0);
INSERT INTO "df" VALUES('MEN''S WHITE LONG-SLEEVED SHIRT',349900,'VALINO',5.0,0);
INSERT INTO "df" VALUES('Gloaming Flanel Veterano Panjang Ashviro Pria ',320000,'Gloaming',NULL,0);
INSERT INTO "df" VALUES('AMK Kemeja Pria Lengan Pendek SHG TATSUKI S/S Maroon',449000,'AMK',4.3,0);
CREATE TABLE rekomendasi (
	"Nama Produk" TEXT, 
	"Harga Produk" INTEGER, 
	"Nama Toko" TEXT, 
	"Rating Produk" FLOAT, 
	"Paling Populer" INTEGER
);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Polos Oxford Slub Regular Fit Pria Abu',399000,'Police Denim',4.9,1);
INSERT INTO "rekomendasi" VALUES('Gloaming Kemeja Flanel Veterano Panjang Aquila Pria',320000,'Gloaming',4.8,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Polos Oxford Slub Navy Regular Fit Pria',399000,'Police Denim',4.9,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Abstrak Printing Cotton Soft Coklat Regular Fit Pria',399000,'Police Denim',4.8,1);
INSERT INTO "rekomendasi" VALUES('Long Sleeve Micro Stripe Shirt',429900,'WOOD',5.0,1);
INSERT INTO "rekomendasi" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford Cream 1069',299000,'Platini',4.7,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Abstrak Printing Cotton Soft Putih Hijau Regular Fit Pria',399000,'Police Denim',4.8,1);
INSERT INTO "rekomendasi" VALUES('Short Sleeve Checks Shirt with Pocket',399900,'WOOD',4.9,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Polos Basic Cotton Soft Regular Fit Lengan Pendek Pria',399000,'Police Denim',4.8,1);
INSERT INTO "rekomendasi" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford Coklat Tua 1069',299000,'Platini',4.9,1);
INSERT INTO "rekomendasi" VALUES('Platini Kemeja Pria Polos Pendek Katun Oxford Hitam Pekat 1069',299000,'Platini',4.9,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Polos Cotton Twill Regular Fit Hijau Tua Pria',399000,'Police Denim',4.9,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Printing Cotton Soft Regular Fit Pria',399000,'Police Denim',4.7,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Printing Cotton Soft Abu Regular Fit Pria',399000,'Police Denim',4.8,1);
INSERT INTO "rekomendasi" VALUES('Greenlight Voyager Men''s Shirt Short Sleeve Regular Fit Cotton Atha C081124',219000,'GREENLIGHT',4.8,1);
INSERT INTO "rekomendasi" VALUES('Platini Kemeja Pria Polos Lengan Pendek Katun Oxford COKLAT MUDA 1069',299000,'Platini',4.8,1);
INSERT INTO "rekomendasi" VALUES('MAGINOT OXFORD 2.0 BLUE Kemeja Casual Slim Fit Lengan Panjang',499000,'Maginot',4.7,1);
INSERT INTO "rekomendasi" VALUES('Greggory Shirts',449900,'X-EIGHT',4.9,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Abstrak Printing Hitam Regular Fit Pria',399000,'Police Denim',4.9,1);
INSERT INTO "rekomendasi" VALUES('Platini Kemeja Pria Lengan Pendek Basic katun oxford Cream  63213',479000,'Platini',4.8,1);
INSERT INTO "rekomendasi" VALUES('BASTIEN - BEIGE WHITE PEPPER Kemeja Flannel Casual Pria Lengan Panjang LS - Top Man Shirt',499900,'Edwin Jeans',4.9,1);
INSERT INTO "rekomendasi" VALUES('Short Sleeve Micro Check Shirt',399900,'WOOD',4.9,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Polos Basic Cotton Soft Choco Brown Regular Fit Lengan Panjang Pria',399000,'Police Denim',4.9,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Printing Cotton Soft Coklat Regular Fit Pria',399000,'Police Denim',4.8,1);
INSERT INTO "rekomendasi" VALUES('JIRO - WHITE Kemeja Lengan Panjang Pria Top Man Shirt Warna White',499900,'Edwin Jeans',4.8,1);
INSERT INTO "rekomendasi" VALUES('BASTIEN - BLACK GREY Kemeja Flannel Casual Pria Lengan Panjang LS - Top Man Shirt',499900,'Edwin Jeans',5.0,1);
INSERT INTO "rekomendasi" VALUES('Platini Kemeja Kotak Pria Lengan Pendek Katun Red Navy 73622 ',399000,'Platini',4.5,1);
INSERT INTO "rekomendasi" VALUES('Cotton Dobby Cheked Shirt KLS604',469500,'Lois Jeans',5.0,1);
INSERT INTO "rekomendasi" VALUES('Kemeja Flanel Panjang Martens Unisex',290000,'Gloaming',4.8,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Printing Cotton Soft Olive Regular Fit Pria',399000,'Police Denim',4.9,1);
INSERT INTO "rekomendasi" VALUES('MOC - Kemeja Batik Pria Lengan Panjang Balereng - White Warna White',379900,'MOC',5.0,1);
INSERT INTO "rekomendasi" VALUES('Linen Blend Slim Fit Shirt - White LS',499000,'VENGOZ',4.6,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Abstrak Printing Navy Regular Fit Pria',399000,'Police Denim',4.9,1);
INSERT INTO "rekomendasi" VALUES('Regular Fit Short Sleeve Oxford Shirt',399900,'WOOD',5.0,1);
INSERT INTO "rekomendasi" VALUES('Kemeja lengan pendek pria formal slim fit black houseofcuff',299000,'House of Cuff',4.5,1);
INSERT INTO "rekomendasi" VALUES('Mahesintra Putih Kemeja Batik Pria Premium Slimfit Lengan Pendek NLN',359000,'ABIROY',3.8,1);
INSERT INTO "rekomendasi" VALUES('Gloaming Kemeja Flanel Veterano Unisex Panjang Delecta',320000,'Gloaming',4.8,1);
INSERT INTO "rekomendasi" VALUES('Cotton Dobby Shirt KLL602',479500,'Lois Jeans',5.0,1);
INSERT INTO "rekomendasi" VALUES('POLICE Kemeja Salur Printing Regular Fit Pria',399000,'Police Denim',5.0,1);
INSERT INTO "rekomendasi" VALUES('Platini Baju Kemeja Pria Lengan Panjang Polos Polinosic Hitam 66100',499000,'Platini',4.9,1);
COMMIT;
