BEGIN TRANSACTION;
CREATE TABLE table_name (
	"Nama Produk" TEXT, 
	"Harga Produk" INTEGER, 
	"Nama Toko" TEXT, 
	"Rating Produk" FLOAT, 
	"Paling Populer" TEXT
);
INSERT INTO "table_name" VALUES('Leopold Kemeja Printing Pria Tree Motive Lengan Pendek Material Rayon ORIGINAL - Multicolor',1422500,'Hamlin',4.0,'Reguler');
INSERT INTO "table_name" VALUES('Cotton Well Light Denim Series in Washed Black | Kemeja Lengan Panjang Denim Hitam',329000,'Cotton Well',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Drury Denim Shirt',599000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Dillion 2 Oxford Shirt',559000,'Hush Puppies',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Tr Adelard Regular Jacket',999000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Mayonaise All Over Print Shirt',559000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Dillion 2 Oxford Shirt',559000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Levi''s Men''s Classic Pocket Standard Fit Shirt (85748-0290)',649900,'Levi''s',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Windermalt Denim Shirt',699000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Mongrell',799000,'Hush Puppies',0.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Dillion 2 Oxford Shirt',559000,'Hush Puppies',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Dillion 2',559000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Mayday',659000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('955 Rushmore Long Sleeve Shirt',999000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Cavano Overshirt Buttoned Jacket',799000,'Hush Puppies',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Lyamm Flannel Overshirt',799000,'Hush Puppies',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Open Collar Print Linen Shirt',1599000,'Superdry',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Stromboli Stand Collar Shirt',559000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Springdale Long Sleeve Shirt',799000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Stromboli Stand Collar Shirt',559000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Bari Long Sleeve Shirt',699000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('90''S Colorblock Corduroy Shirt',799000,'Hush Puppies',4.5,'Reguler');
INSERT INTO "table_name" VALUES('Downy Printed Shirt',659000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Relaxed Fit Western Shirt (A1919-0040)',649900,'Levi''s',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Oxfoore Shirt',699000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Pablo Short Sleeve Shirt',599900,'Cotton On',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Short Sleeved Cotton Shirt',1159000,'Selected Homme',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Grova All Over Print Shirt',559000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Box Fit Short Sleeve Shirt',599900,'Cotton On',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Jimnu Flannel Shirt',659000,'Hush Puppies',3.0,'Reguler');
INSERT INTO "table_name" VALUES('Macadamia Stand Collar Shirt',599000,'Hush Puppies',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Josue Relaxed Resort Shirt',559000,'Hush Puppies',0.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Oxcon Short Sleeve Business Shirt soft cotton Bamboo',255000,'Oxcon',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Harley-Davidson® Stacked Bar & Shield Long Sleeve Plaid Shirt',2493764,'Harley Davidson',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Drury Denim Shirt',599000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('90''S Colorblock Corduroy Shirt',799000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Zhou Stand Collar Shirt',599000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Quinoa Stand Collar Shirt',659000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Downy Printed Shirt',659000,'Hush Puppies',4.7,'Paling Populer');
INSERT INTO "table_name" VALUES('Nile Stand Collar Shirt',659000,'Hush Puppies',4.5,'Paling Populer');
INSERT INTO "table_name" VALUES('Conway Shirt',699000,'Hush Puppies',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Minuti',599000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Prince Printed Shirt',659000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Jimnu Flannel Shirt',659000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Nautical Sheringham Resort Shirt',559000,'Hush Puppies',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Conway Shirt',699000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Toscano Stand Collar Shirt',599000,'Hush Puppies',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Zhou Stand Collar Shirt',599000,'Hush Puppies',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Trieste Shirt',599000,'Hush Puppies',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Padova Long Sleeve Shirt',699000,'Hush Puppies',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Orano Buttoned Down Ls Shirt',699000,'Hush Puppies',0.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Robiola Stand Collar Shirt',659000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Tr Jourdy Sss',599000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Robiola Stand Collar Shirt',659000,'Hush Puppies',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Orano Buttoned Down Ls Shirt',699000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Minuti',599000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Cacao Stand Collar Shirt',659000,'Hush Puppies',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Premium Slim Fit Sateen Shirt With Shawl Collar',759000,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Karuka Stand Collar Shirt',599000,'Hush Puppies',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Grova All Over Print Shirt',559000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Kola Stand Collar Shirt',599000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Stromboli Stand Collar Shirt',559000,'Hush Puppies',0.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Kola Stand Collar Shirt',599000,'Hush Puppies',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Stand Collar Shirt',659000,'Hush Puppies',4.0,'Reguler');
INSERT INTO "table_name" VALUES('Kola Stand Collar Shirt',599000,'Hush Puppies',4.6,'Paling Populer');
INSERT INTO "table_name" VALUES('Macadamia Stand Collar Shirt',599000,'Hush Puppies',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Cotton Well Kemeja Lengan Panjang Basic Polos Abu | Long Sleeve Oxford Grey',200000,'Cotton Well',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Dolma Stand Collar Shirt',659000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Vasemir',659000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Karuka Stand Collar Shirt',599000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Branzino Stand Collar Shirt',659000,'Hush Puppies',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Toscano Stand Collar Shirt',599000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Karuka Stand Collar Shirt',599000,'Hush Puppies',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Byron Stand Collar Shirt',599000,'Obermain',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Orano Buttoned Down Ls Shirt',699000,'Hush Puppies',4.5,'Paling Populer');
INSERT INTO "table_name" VALUES('90S Klaus Flannel Long Sleeve Shirt',659000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Studios Casual Linen Short Sleeves Shirt',1499000,'Superdry',3.0,'Reguler');
INSERT INTO "table_name" VALUES('Briscoe Stand Collar Shirt',599000,'Obermain',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Vasemir',659000,'Hush Puppies',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Baldwin Stand Collar Shirt',699000,'Obermain',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Branzino Stand Collar Shirt',659000,'Hush Puppies',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Arnold Oversized Shirt',799000,'Obermain',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Amber Mandarin Collar Shirt',799000,'Obermain',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Studios Casual Linen Shirt',1499000,'Superdry',3.0,'Reguler');
INSERT INTO "table_name" VALUES('Himmel Denim Shirt',659000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Tirade Jacket',1199000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Vintage Loom Short Sleeves Shirt - Original & Vintage',1249000,'Superdry',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Arnold Oversized Shirt',799000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('958 Chester Ss Regular Formal Shirt',899000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('955 Franklin',899000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('955 Chester Ss Regular Formal Shirt',899000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Logo Long Sleeve Shirt',2659000,'US POLO ASSN',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Padrone Stand Collar Stripe Shirt',599000,'Hush Puppies',4.8,'Reguler');
INSERT INTO "table_name" VALUES('957 Chester Ss Regular Formal Shirt',899000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('955 Franklin Shirt',899000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Bari Long Sleeve Shirt',699000,'Hush Puppies',4.3,'Reguler');
INSERT INTO "table_name" VALUES('Josue Relaxed Resort Shirt',559000,'Hush Puppies',4.5,'Paling Populer');
INSERT INTO "table_name" VALUES('956 Chester Ss Regular Formal Shirt',899000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('956 Avalon Long Sleeve Shirt',999000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Cotton Well Badr Stand Collar Shirt Terracotta | Kemeja Koko Lengan Panjang Coklat Bata Terakota',200000,'Cotton Well',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Cotton Well Flannel Shirt Cloud Grey',299000,'Cotton Well',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Josue Relaxed Resort Shirt',559000,'Hush Puppies',4.5,'Reguler');
INSERT INTO "table_name" VALUES('956 Weston Long Sleeve Shirt',999000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Pinida Stand Collar Shirt With Pintuck Detail',699000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('957 Avalon Long Sleeve Shirt',999000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Truro',699000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Stromboli Stand Collar Shirt',559000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('955 Avalon Long Sleeve Shirt',999000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('955 Weston Long Sleeve Shirt',999000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Centie Solid Linen Shirt',1199000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('90''S Resort Shirt',559000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Men''s Long Sleeves Shirt',1449000,'Petrol Industries',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Padova Long Sleeve Shirt',699000,'Hush Puppies',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Pablo Short Sleeves Shirt',599900,'Cotton On',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Tim',799000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Truro',699000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Safron Stand Collar Shirt',659000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('90S Klaus Flannel Long Sleeve Shirt',659000,'Hush Puppies',0.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Orano Buttoned Down Ls Shirt',699000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Quinoa Stand Collar Shirt',659000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Minuti',599000,'Hush Puppies',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Padova Long Sleeve Shirt',699000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('956 Rushmore Long Sleeve Shirt',999000,'Hush Puppies',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Toscano Stand Collar Shirt',599000,'Hush Puppies',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Toscano Stand Collar Shirt',599000,'Hush Puppies',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Cny Yan Stand Collar Shirt',599000,'Hush Puppies',0.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Palma Short Sleeve Shirt',499900,'Cotton On',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Point Collar Cotton Pique Oversized Fit Overshirt - BOSS Orange',3829000,'BOSS',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Linen Shirt',2849000,'US POLO ASSN',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Denhag Flanel Shirt',599000,'Obermain',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Cabana Short Sleeve Shirt',599900,'Cotton On',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Bennet Embroidered Stand Collar Shirt',799000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Cotton Well Badr Stand Collar Shirt Green | Kemeja Koko Lengan Panjang Hijau',299000,'Cotton Well',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Harley-DavidsonPerformance Plaid Shirt',2493764,'Harley Davidson',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Cavano Overshirt Buttoned Jacket',799000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Buster',659000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Trieste Shirt',599000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Bari Long Sleeve Shirt',699000,'Hush Puppies',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Bellamy Stand Collar Shirt',599000,'Obermain',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Trieste Shirt',599000,'Hush Puppies',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Padova Long Sleeve Shirt',699000,'Hush Puppies',4.0,'Reguler');
INSERT INTO "table_name" VALUES('Overshirt',599900,'H&M',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Bellamy Stand Collar Shirt',599000,'Obermain',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Barney Stand Collar Shirt',599000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Poncho',659000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Dolma Stand Collar Shirt',659000,'Hush Puppies',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Barbosa',599000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Rolland Shirt',599000,'Hush Puppies',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Nile Stand Collar Shirt',659000,'Hush Puppies',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Regular Fit Teddy overshirt',699900,'H&M',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Long Sleeves Shirt',759000,'Jack & Jones',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Regular Fit Pima cotton resort shirt',599900,'H&M',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Lovel Zip Overshirt  -  BOSS Orange',4179000,'BOSS',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Palma Short Sleeves Shirt',509000,'Cotton On',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Warm Shirt',1009000,'LUFIAN',1.0,'Reguler');
INSERT INTO "table_name" VALUES('Bentley Stand Collar Shirt',699000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Reef RXD SS linen SMART',599900,'H&M',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Cotton Workwear Long Sleeves Shirt',1489000,'Superdry',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Basic Fitted Shirt',499000,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Plain Oversized Shirt',789000,'Trendyol',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Reef RXD SS linen SMART',599900,'H&M',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Long Sleeved Shirt',1139000,'Selected Homme',4.5,'Reguler');
INSERT INTO "table_name" VALUES('Regular Fit Pima cotton resort shirt',599900,'H&M',0.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Oxcon Long Sleeve Business Shirt soft cotton White',265000,'Oxcon',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Harley-Davidson Screamin'' Eagle® Short Sleeve Shirt',2160585,'Harley Davidson',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Briscoe Stand Collar Shirt',599000,'Obermain',4.6,'Reguler');
INSERT INTO "table_name" VALUES('Conhag Flanel Shirt',599000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Striped Collared Shirt',939000,'Trendyol',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Dion Zipper Shirt',559000,'Obermain',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Slim Fit Shirt',719000,'Trendyol',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Faro Long Sleeves Shirt',1049000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Umbert Shirt',1089000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('CLTN Seer Shirt',1089000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Conhag Flanel Shirt',599000,'Obermain',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeve Brody Overshirt',1419000,'Selected Homme',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeves Woven Shirt',609000,'ARMA',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Slim Fit Collared Shirt',769000,'Trendyol',4.6,'Reguler');
INSERT INTO "table_name" VALUES('Wavy Pattern Resort Shirt',559000,'Obermain',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Brook Melange Long Sleeves Shirt',829000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Linen-Blend Long Sleeves Shirt',2849000,'US POLO ASSN',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Ray Outer Shirt',559000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi’s® Men’s Authentic Button-Down Shirt (A7210-0012)',649900,'Levi''s',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('EQ Milan license AOP ss STREET',399900,'H&M',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Merchant Shirt',1489000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Miles REG odyed stripe oxford',399900,'H&M',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeves Shirt',989000,'Trendyol',3.0,'Reguler');
INSERT INTO "table_name" VALUES('Overshirt',599900,'H&M',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Slim-Fit Textured Cotton Suit Shirt',1099000,'MANGO Man',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Classic Pocket Standard Fit Shirt (85748-0272)',749900,'Levi''s',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Sunset Pocket Standard Fit Shirt (85746-0150)',749900,'Levi''s',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Levi’s® Men’s Jackson Worker Overshirt (19573-0243)',749900,'Levi''s',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Slim Fit Fine-Striped Cotton Shirt',1099000,'MANGO Man',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Men''s Long Sleeves shirt',1209000,'Petrol Industries',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Byron Stand Collar Shirt',599000,'Obermain',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Oxcon Short Sleeve Business Shirt soft cotton Black',255000,'Oxcon',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Cotton Well Lyon Waffle Shirt Mint Green',259000,'Cotton Well',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Textured Shirt',809000,'Trendyol',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi’s® Men’s Authentic Button-Down Shirt (A7210-0018)',749900,'Levi''s',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Bay Vertical Stripe Pattern Shirt',559000,'Obermain',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Studios Casual Linen Long Sleeves Shirt',1599000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Men''s Long Sleeves Shirt',1209000,'Petrol Industries',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Short-Sleeve Banded Collar Shirt (69891-0017)',649900,'Levi''s',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Bay Vertical Stripe Pattern Shirt',559000,'Obermain',4.5,'Paling Populer');
INSERT INTO "table_name" VALUES('Surplus Canvas Overshirt',1999000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Ray Outer Shirt',559000,'Obermain',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Sunset Camp Shirt (72625-0091)',649900,'Levi''s',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Finn',559000,'Obermain',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Briscoe Stand Collar Shirt',599000,'Obermain',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Conhag Flanel Shirt',599000,'Obermain',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Caspian Vertical Stripe Pattern Shirt',599000,'Obermain',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Vintage Military Overshirt',1419000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Finn',559000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Bay Vertical Stripe Pattern Shirt',559000,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi’s® Sunset Camp Shirt (72625-0101)',649900,'Levi''s',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Barstow Standard Fit Western Shirt (85744-0072)',749900,'Levi''s',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi’s® Sunset Camp Shirt (72625-0097)',649900,'Levi''s',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Authentic Button-Down Shirt (A7210-0005)',649900,'Levi''s',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Authentic Button-Down Shirt (A7210-0007)',599900,'Levi''s',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Classic Pocket Standard Fit Shirt (85748-0263)',649900,'Levi''s',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Relaxed Fit Western Shirt (A1919-0043)',649900,'Levi''s',3.5,'Reguler');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Sunset Camp Shirt (72625-0093)',649900,'Levi''s',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Boxy Paper Touch Shirt',1159000,'Selected Homme',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Boxy Casper Waffle Shirt',1139000,'Selected Homme',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Basic Shirt',879000,'Trendyol',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Short Sleeves Jeff Resort Shirt',759000,'Jack & Jones',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Short Lamore Shirt',839000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Palma Short Sleeves Shirt',499900,'Cotton On',4.7,'Reguler');
INSERT INTO "table_name" VALUES('Cotton Well Badr Stand Collar Shirt Black | Kemeja Koko Lengan Panjang Hitam',200000,'Cotton Well',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Mens Gray Buttoned Down Classic Collar Dobby Pocket Regular Fit Shirt',1309000,'Avva',0.0,'Reguler');
INSERT INTO "table_name" VALUES('LEGOLAS SS RESORT SHIRT',299900,'H&M',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeve Pocket Shirt',1109000,'Trendyol',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Bill Long Sleeve Shirt',1159000,'Selected Homme',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Vintage Resort Short Sleeve Shirt',1249000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Military Short Sleeves Shirt',1379000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Men''s Long Sleeve Check Shirt',1669000,'Petrol Industries',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Pakers Shirt',759000,'DIVERSE',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Marshall Band Long Sleeves Shirt',979000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Moose Checked Overshirt',1639000,'Petrol Industries',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Jeff Marbella Resort Shirt',829000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Bardot Sleeves Poplin Midi Dress',1669000,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Slim Fit Shirt',1049000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeve Super Oversized Shirt',919000,'Topman',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Latin Shirt',1159000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Dropped Shoulder Oversized Revere Shirt',759000,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Regular Striped Shirt',1009000,'Trendyol',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('BORIS SS SHIRT',299900,'H&M',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Joe Long Sleeves Mao Collar Shirt',619000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Scripted Embroidery Shirt',309000,'ARMA',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Vintage Bowling Shirt',1559000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Riviera Short Sleeve Shirt',579000,'Cotton On',4.6,'Reguler');
INSERT INTO "table_name" VALUES('ELLIOT OVZ LS',499900,'H&M',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Skinny Fit Shirt With Grandad Collar',699000,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Basic Shirt',839000,'DIVERSE',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Jeff Rotary Resort Shirt',759000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Men''s Long Sleeve Uni Shirt',2149000,'Petrol Industries',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Vintage Bowling S/S Shirt',1559000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Harley-Davidson Year of The Dragon Short Sleeve Shirt',0,'Harley Davidson',5.0,'Reguler');
INSERT INTO "table_name" VALUES('MTS91 Kemeja Baseball Oversize Jersey Garis Putih "Osaka" Hitam',0,'Third Day',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Darren Flannel Overshirt',0,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Basic Shirt',0,'DIVERSE',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Joe Long Sleeves Plain Shirt',0,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Bandama SH Shirt',0,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Pablo Short Sleeve Shirt',0,'Cotton On',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Textured Overshirt',0,'Trendyol',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Box Fit Short Sleeve Shirt',0,'Cotton On',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Misko Shirt',0,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Cabana Short Sleeve Shirt',0,'Cotton On',5.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Gouff Shirt',0,'DIVERSE',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Skinny Fit Shirt With Grandad Collar',0,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeves Collared Shirt',0,'Jack & Jones',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeved Shirt',0,'Selected Homme',4.5,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeve Overshirt',0,'Petrol Industries',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Oversized Fit Shirt',0,'Topman',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeve Shirt',0,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Platini Kemeja Pria Lengan Pendek Basic Katun Oxford Hijau Sage 63251',0,'Platini',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Denim Overshirt',0,'Trendyol',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Floral Printed Shirt',0,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Wedding Premium Skinny Sateen Shirt',0,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Pablo Short Sleeves Shirt',0,'Cotton On',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Linen Short Sleeve Shirt',0,'Cotton On',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Platini Kemeja Basic Hitam Pria Lengan Panjang Katun Poplin 66302',0,'Platini',4.8,'Paling Populer');
INSERT INTO "table_name" VALUES('Platini Kemeja Motif Pria Lengan Pendek Katun Broken White 132185',0,'Platini',4.7,'Paling Populer');
INSERT INTO "table_name" VALUES('Cabana Short Sleeve Shirt',0,'Cotton On',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Barney Stand Collar Shirt',0,'Obermain',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Resurrection Shirt - Original & Vintage',0,'Superdry',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Relaxed Fit Satin resort shirt',0,'H&M',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Flock Print Denim Resort Shirt',0,'Denim Project',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Bentley Stand Collar Shirt',0,'Obermain',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Platini Kemeja Pria Lengan Panjang Katun Denim Biru Muda 76421',0,'Platini',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Striped Deep Revere Satin Shirt',0,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Kemeja tangan panjang Formal Stretch oxcon White',385000,'Oxcon',4.8,'Reguler');
INSERT INTO "table_name" VALUES('Regular Fit Teddy overshirt',699900,'H&M',5.0,'Reguler');
INSERT INTO "table_name" VALUES('LUCAS REG LINEN LS SHIRT',429900,'H&M',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Levi''s® Men''s Sunset Camp Shirt (72625-0085)',549900,'Levi''s',4.7,'Paling Populer');
INSERT INTO "table_name" VALUES('Diagonal Stripes Revere Shirt',699000,'ASOS Design',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Cotton Woven Shirt',539000,'ARMA',5.0,'Reguler');
INSERT INTO "table_name" VALUES('CLTN Bartsh Shirt',939000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Regular Fit Viscose shirt',349900,'H&M',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Martin Mandarin Linen',499900,'H&M',5.0,'Reguler');
INSERT INTO "table_name" VALUES('MOC Kemeja Batik Lengan Pendek Pria KRADEV - WHITE',359900,'MOC',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Linen Short Sleeve Shirt',599900,'Cotton On',4.9,'Reguler');
INSERT INTO "table_name" VALUES('Joshua Aruba Shirt',649000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Regular-Fit Striped Cotton-Linen Shirt',1099000,'MANGO Man',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Vintage Cord Overshirt',1599000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('MISKO LG Shirt',919000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeve Casual Shirt',979000,'Trendyol',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Canvas Workwear Overshirt',1869000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Canvas Workwear Overshirt',1709000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Long Sleeve Plain Shirt',649000,'Trendyol',5.0,'Reguler');
INSERT INTO "table_name" VALUES('Polkadot Shirt',649000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Marshall Band Shirt',979000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Riviera Short Sleeves Shirt',399900,'Cotton On',4.6,'Reguler');
INSERT INTO "table_name" VALUES('Wool Miller Overshirt',1609000,'Superdry',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Checked Shirt',399000,'Trendyol',3.8,'Reguler');
INSERT INTO "table_name" VALUES('Slim Fit Grandad Collar Shirt',869000,'Trendyol',4.6,'Reguler');
INSERT INTO "table_name" VALUES('Basic Shirt',829000,'Trendyol',4.9,'Reguler');
INSERT INTO "table_name" VALUES('EQ Zed solid RXD ss STREET',299900,'H&M',4.9,'Paling Populer');
INSERT INTO "table_name" VALUES('Santorini Wide Fit Denim Overshirt',1049000,'Jack & Jones',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Henley Shirt',2899000,'BOSS',0.0,'Paling Populer');
INSERT INTO "table_name" VALUES('Basic Short Sleeves Linen Shirt',719000,'DIVERSE',0.0,'Reguler');
INSERT INTO "table_name" VALUES('Slim Fit Collared Shirt',809000,'Trendyol',4.6,'Reguler');
COMMIT;
